<script lang="ts">
import { getContext } from "svelte";

// biome-ignore lint/correctness/noUnusedVariables: used in Svelte template
const getFlavour = getContext<() => string>("flavour");
</script>

<svelte:head>
	<title>Learn — link42</title>
	<meta
		name="description"
		content="Security intelligence education. Learn about the ISM, Essential Eight, threat intelligence, vulnerability management, and risk assessment."
	/>
	<meta property="og:title" content="Learn — link42" />
	<meta property="og:description" content="Security intelligence education. Learn about the ISM, Essential Eight, threat intelligence, vulnerability management, and risk assessment." />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="https://link42.app/learn" />
	<meta property="og:site_name" content="Link42" />
	<meta name="twitter:card" content="summary" />
	<meta name="twitter:title" content="Learn — link42" />
	<meta name="twitter:description" content="Security intelligence education. Learn about the ISM, Essential Eight, threat intelligence, vulnerability management, and risk assessment." />
	<link rel="canonical" href="https://link42.app/learn" />
</svelte:head>

<div class="cl-main cl-main--learn">
	<div class="learn-hero">
		<h1 class="cl-title">Security Intelligence, Explained</h1>
		
		{#if getFlavour() === 'factual'}
			<p class="cl-sub">
				A comprehensive guide for security practitioners, CISOs, IT managers, compliance officers, and anyone trying to understand Australian cybersecurity requirements. We break down complex frameworks, threat intelligence, and vulnerability management into actionable knowledge.
			</p>
		{:else}
			<p class="cl-sub">
				Because reading 800 pages of government PDFs isn't anyone's idea of a good time. Whether you're a CISO trying to justify budget, an IT manager drowning in acronyms, or just someone who wants to know what the Essential Eight actually means without falling asleep—you're in the right place.
			</p>
		{/if}
	</div>

	<div class="learn-topic-grid">
		<a href="/learn/frameworks" class="learn-topic-card">
			<h2>Frameworks</h2>
			<p>Understand the ISM, Essential Eight, NZISM, and how they protect Australian systems.</p>
		</a>
		<a href="/learn/threat" class="learn-topic-card">
			<h2>Threat Intelligence</h2>
			<p>What threat data is, where it comes from, and how to act on it.</p>
		</a>
		<a href="/learn/vulnerability" class="learn-topic-card">
			<h2>Vulnerabilities</h2>
			<p>CVEs, scoring systems, and how to prioritise what to fix first.</p>
		</a>
		<a href="/learn/risk" class="learn-topic-card">
			<h2>Risk Assessment</h2>
			<p>How threat, vulnerability, and business context combine into actionable risk.</p>
		</a>
	</div>

	<div class="lic-section">
		<h2>Where to start</h2>
		<ul>
			<li><strong>New to cybersecurity?</strong> Start with <a href="/learn/frameworks">Frameworks</a>, then <a href="/learn/vulnerability">Vulnerabilities</a>.</li>
			<li><strong>Security practitioner?</strong> Start with <a href="/learn/threat">Threat Intelligence</a>, then <a href="/learn/risk">Risk Assessment</a>.</li>
			<li><strong>CISO or board member?</strong> Start with <a href="/learn/risk">Risk Assessment</a>, then <a href="/learn/frameworks">Frameworks</a>.</li>
		</ul>
	</div>

	<div class="learn-attribution">
		<span class="lic-tag">Content generated by Claude, reviewed by Iain Dickson. Toggle between factual and irreverent voices using the sidebar control.</span>
	</div>
</div>
